update template plugin
scipion-em/scipion-em-template pull request #5
Opened 2024-03-06 15:42 UTC by azazellochg

2024-03-07 14:55 UTC, pconesa commented on MANIFEST.in
> +include myplugin/protocols.conf
Should we add requirements.txt?

2024-03-07 14:58 UTC, azazellochg commented on MANIFEST.in
> +include myplugin/protocols.conf
it's kind of inexplicitly there: include *.txt

2024-03-07 15:11 UTC, pconesa commented on myplugin/tests/__init__.py
> +# Module to declare viewers
Thi should say tests, right?

2024-03-07 15:12 UTC, pconesa requested changes
Minor changes. Good to create steps as methods not strings.

2024-03-11 17:24 UTC, pconesa approved these changes

2024-03-11 17:24 UTC, merged